<?php

/**
 * CashTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CashTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CashTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cash');
    }
}