<?php

/**
 * CourseClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseClient');
    }
}