<?php

/**
 * Package
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    camaradecomercio
 * @subpackage model
 * @author     $AUTHOR
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Package extends BasePackage
{
}
