<?php

/**
 * sfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserProfile');
    }
    
    public function getInsurancedUsers()
    {
        $users = $this->createQuery("c")
        ->leftJoin('c.User AS u')
        ->leftJoin('u.Groups AS g')
        ->where('g.id = ? OR g.id = ?', array(sfConfig::get('app_groups_adscript'),sfConfig::get('app_groups_company')))
        ->execute();

        return $users;
    }
}