<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    camaradecomercio
 * @subpackage model
 * @author     $AUTHOR
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
    public function postDelete($event)
    {
        $sfGuardUser = SfGuardUserTable::getInstance()->find($this->getSfGuardUserId());
        $sfGuardUser->delete();
    }
    
    public function getAge()
    {
        $year = date('Y', time());
        $month = date('m', time());
        $day = date('d', time());
        $birthYear = date('Y', strtotime($this->getBirthdate()));
        $birthMonth = date('m', strtotime($this->getBirthdate()));
        $birthDay = date('d', strtotime($this->getBirthdate()));
        
        $age = ($year-$birthYear);
        
        if ($month < $birthMonth){
            $age--;
        }
        else if($birthMonth == $month)
        {
            if($birthDay > $day)
            {
                $age--;
            }
        }
        return $age;
    }
}
