<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function retrieveOnlyTeachers()
    {
        return $this->createQuery("a")
                ->leftJoin("a.Groups g")
                ->where("g.id = ?", sfConfig::get("app_groups_teacher"))
                ->execute();
    }

    public function retrieveOnlyStudents()
    {
        return $this->createQuery("a")
                ->leftJoin("a.Groups g")
                ->where("g.id = ?", sfConfig::get("app_groups_student"))
                ->execute();
    }
    
    public function retrieveOnlyAdscripts()
    {
        return $this->createQuery("a")
                ->leftJoin("a.Groups g")
                ->where("g.id = ?", sfConfig::get("app_groups_adscript"))
                ->execute();
    }
    
    public function retrieveOnlyCompanies()
    {
        return $this->createQuery("a")
                ->leftJoin("a.Groups g")
                ->where("g.id = ?", sfConfig::get("app_groups_company"))
                ->execute();
    }
}