<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcash extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cash', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'course_client_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 8,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Ingreso',
              1 => 'Egreso',
              ),
              'length' => NULL,
             ),
             'amount' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'notnull' => true,
              'length' => 18,
             ),
             'concept' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Gastos de Oficina',
              1 => 'Pago de servicios',
              2 => 'Pago de Honorarios',
              3 => 'Capacitación',
              4 => 'Alquiler del Salón',
              5 => 'Sueldos',
              6 => 'Gastos varios',
              7 => 'Ingresos varios',
              8 => 'Donaciones',
              ),
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('cash');
    }
}