<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpackage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('package', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             'teoric_course_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'notnull' => true,
              'length' => 18,
             ),
             'practices_number' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('package');
    }
}