<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addclient extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('client', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             'lastname' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 150,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             'cell_phone' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 64,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('client');
    }
}