<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfguarduserprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'sf_guard_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'company_id' => 
             array(
              'type' => 'integer',
              'comment' => 'Empresa a la que pertenece, no es obligatorio',
              'length' => 8,
             ),
             'health_insurance_id' => 
             array(
              'type' => 'integer',
              'comment' => 'Obra social a la que está asociado, no es obligatorio porque depende del tipo de usuario',
              'length' => 8,
             ),
             'birthdate' => 
             array(
              'type' => 'date',
              'comment' => 'Fecha de nacimiento para calcular precio en base a la edad',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_user_profile');
    }
}